export const USER_REGISTER_FAILURE = "USER_REGISTER_FAILURE";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const USER_LOGIN_ERRORS = "USER_LOGIN_ERRORS";
export const USER_LOG_OUT = "USER_LOG_OUT";

export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILES = "GET_PROFILES";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";
export const PROFILE_FIELDS_ERROR = "PROFILE_FIELDS_ERROR";
export const GET_ERRORS = "GET_ERRORS";
